FROM node:22-alpine AS base
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install --frozen-lockfile

# Build frontend
COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview"]