services:
  swapi_app:
    container_name: swapi_app_dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - caddy

  frontend:
    container_name: frontend_dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - caddy

  postgres_db:
    image: postgres:17.4-alpine3.21
    env_file:
      - server/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - caddy

networks:
  caddy:

volumes:
  pgdata_dev:
