networks:
  caddy:
services:
  caddy:
    container_name: caddy
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/server/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - frontend:/static/client
    networks:
      - caddy
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.2"
  swapi_app:
    container_name: swapi_app
    env_file:
      - server/.env
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    networks:
      - caddy
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.3"
    volumes:
      - frontend:/usr/src/app/static/client
  postgres_db:
    container_name: postgres_db
    image: postgres:17.4-alpine3.21
    env_file:
      - server/.env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5433:5432"
    networks:
      - caddy
    deploy:
      resources:
        limits:
          memory: 128M
volumes:
  caddy_data:
  caddy_config:
  frontend:
