apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Prometheus service address in the container
    isDefault: true
    jsonData:
      timeInterval: "5s"
