services:
  swapi_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
