networks:
  caddy:
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/../client/dist:/static/client
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
  swapi_app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - caddy
  postgres_db:
    container_name: postgres_db
    env_file:
      - .env
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5433:5432'
    networks:
      - caddy
volumes:
  caddy_data:
  caddy_config:
