services:
  swapi_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  postgres_db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5433:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'F7Hl3*HU8g67#bh91'
      POSTGRES_DB: starwars_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
